version: '3'

includes:
  utl:
    taskfile: ./task/utl.yml
    dir: .
  node:
    taskfile: ./task/node.yml
    dir: ./node-pkgs

silent: true

tasks:
  default:
    desc: -> utl:lint
    cmds:
      - task: utl:lint

  reload:
    desc: -> utl:reload
    cmds:
      - task: utl:reload
    aliases: [re]

  check:
    desc: -> node:update:check
    cmds:
      - task: node:update:check

  update:
    desc: -> node:update & utl:reload
    cmds:
      - task: node:update
      - task: utl:reload
    aliases: [up]

  install:
    desc: -> node:install & utl:reload
    cmds:
      - task: node:install
      - task: utl:reload
    aliases: [add]

  uninstall:
    desc: -> node:uninstall & utl:reload
    cmds:
      - task: node:uninstall
      - task: utl:reload
    aliases: [remove, rm]
