version: '3'

vars:
  NODEPKGS: node-pkgs
  NODE_SHELL: nix develop .#node -c

tasks:
  default:
    cmds:
      - task: lint

  lint:
    desc: "[default] Run linters"
    cmds:
      - treefmt --config-file ./linter/treefmt.toml
    silent: true

  reload:
    desc: Reload Nix devShell environment
    cmds:
      - direnv reload
    silent: true

  add:
    desc: Add package to package.json and package-lock.json (requires args e.g. <PackageName>@<Version>)
    aliases: [install]
    dir: ./{{.NODEPKGS}}
    preconditions:
      - sh: test -n "{{.CLI_ARGS}}"
        msg: "Package name is required, e.g. task add -- zenn-cli"
    cmds:
      - "{{.NODE_SHELL}} npm install -D {{.CLI_ARGS}} --package-lock-only"
      - task: reload
    silent: true

  remove:
    desc: Remove package from package.json and package-lock.json (requires args e.g. <PackageName>)
    aliases: [uninstall, rm]
    dir: ./{{.NODEPKGS}}
    preconditions:
      - sh: test -n "{{.CLI_ARGS}}"
        msg: "Package name is required, e.g. task remove -- zenn-cli"
    cmds:
      - "{{.NODE_SHELL}} npm uninstall -D {{.CLI_ARGS}} --package-lock-only"
      - task: reload
    silent: true

  update-check:
    desc: Check for outdated packages before update
    dir: ./{{.NODEPKGS}}
    cmds:
      - "{{.NODE_SHELL}} ncu"
    silent: true

  update-packages:
    desc: Update packages to the latest version (only package.json)
    dir: ./{{.NODEPKGS}}
    cmds:
      - "{{.NODE_SHELL}} ncu -u"
    silent: true

  update-lockfile:
    desc: Refresh package-lock.json from package.json
    dir: ./{{.NODEPKGS}}
    cmds:
      - "{{.NODE_SHELL}} npm install --package-lock-only"
    silent: true

  update:
    desc: Update packages and refresh package-lock.json
    aliases: [up]
    dir: ./{{.NODEPKGS}}
    cmds:
      - task: update-packages
      - task: update-lockfile
      - task: reload
    silent: true
