version: '3'

vars:
  NODEPKGS: node-pkgs
  NODE_SHELL: nix develop .#node -c

silent: true

tasks:
  default:
    deps:
      - lint

  lint:
    desc: "[default] Run linters"
    cmds:
      - treefmt --config-file ./linter/treefmt.toml

  reload:
    desc: Reload Nix devShell environment
    cmds:
      - direnv reload

  node:install:
    desc: Add package to package.json and package-lock.json (requires args e.g. <PackageName>@<Version>)
    aliases: [install, add]
    dir: ./{{.NODEPKGS}}
    preconditions:
      - sh: test -n "{{.CLI_ARGS}}"
        msg: "Package name is required, e.g. task add -- zenn-cli"
    cmds:
      - "{{.NODE_SHELL}} npm install -D {{.CLI_ARGS}} --package-lock-only"
      - task: reload

  node:uninstall:
    desc: Remove package from package.json and package-lock.json (requires args e.g. <PackageName>)
    aliases: [uninstall, remove, rm]
    dir: ./{{.NODEPKGS}}
    preconditions:
      - sh: test -n "{{.CLI_ARGS}}"
        msg: "Package name is required, e.g. task remove -- zenn-cli"
    cmds:
      - "{{.NODE_SHELL}} npm uninstall -D {{.CLI_ARGS}} --package-lock-only"
      - task: reload

  node:update:check:
    desc: Check for outdated packages before update
    dir: ./{{.NODEPKGS}}
    cmds:
      - "{{.NODE_SHELL}} ncu"

  node:update:packages:
    desc: Update packages to the latest version (only package.json)
    dir: ./{{.NODEPKGS}}
    cmds:
      - "{{.NODE_SHELL}} ncu -u"

  node:update:lockfile:
    desc: Refresh package-lock.json from package.json
    dir: ./{{.NODEPKGS}}
    cmds:
      - "{{.NODE_SHELL}} npm install --package-lock-only"

  node:update:
    desc: Update packages and refresh package-lock.json
    aliases: [update, up]
    dir: ./{{.NODEPKGS}}
    deps:
      - node:update:packages
      - node:update:lockfile
      - reload
