# Maximum number of allowed retries before a link is declared dead.
max_retries = 2

# Website timeout from connect to response finished.
timeout = 10

## Configured by CLI arguments (see issue #13)
# Root path to use when checking absolute local links, must be an absolute path
# root_dir = "/home/ryu/dev/zenn_contents"
