[formatter.md]
command = "markdownlint-cli2"
options = ["--config", "linter/.markdownlint-cli2.jsonc"] 
includes = ["articles/*.md"]
priority = 1

[formatter.text]
command = "textlint"
options = ["--config", "linter/.textlintrc.json"] 
includes = ["articles/*.md"]
priority = 2

[formatter.url]
command = "lychee"
options = ["--timeout", "10", "--max-retries", "2"] 
includes = ["articles/*.md"]
priority = 3

[formatter.spell]
command = "cspell"
includes = ["articles/*.md"]
priority = 4

[global]
excludes = [
    "articles/00341ed49b7935.md",
    "articles/007bff63247432.md",
    "articles/0a5f92301e3b6f.md",
    "articles/10771998f8aef8.md",
    "articles/231ec8c4493e74.md",
    "articles/479478033f16da.md",
    "articles/5e7cd43586b68a.md",
    "articles/5f91a2fd269ffd.md",
    "articles/642043cbae5f21.md",
    "articles/6f6fe5c8746798.md",
    "articles/867357519bcb0d.md",
    "articles/8b497c93c0f652.md",
    "articles/987116391625bf.md",
    "articles/a0f4c2f00fdc40.md",
    "articles/bab9538507644c.md",
    "articles/c2fa1ded4d54ac.md",
    "articles/c983fc42a138cf.md",
    "articles/d1b900cd49cbcf.md",
    "articles/d695cebc50a888.md",
    "articles/e4fc4aa3357870.md",
    "articles/f44452ebca9b14.md",
    "articles/32ff89d4e14815.md",
    "articles/6678b0c0fb0d27.md"
]
